//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace avaliacao1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("avaliacao1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cd1 {
            get {
                object obj = ResourceManager.GetObject("cd1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user mG9S7zDsPbw=
        ///admin mG9S7zDsPbw=.
        /// </summary>
        internal static string db_users {
            get {
                return ResourceManager.GetString("db_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;album&gt;
        ///  &lt;cd nome=&quot;cd1&quot; titulo=&quot;titulo1&quot; genero=&quot;genero1&quot; autor=&quot;autor1&quot; ano=&quot;2010&quot; imagem=&quot;cd1.jpg&quot; /&gt;
        ///  &lt;cd nome=&quot;cd2&quot; titulo=&quot;titulo2&quot; genero=&quot;genero2&quot; autor=&quot;autor2&quot; ano=&quot;2012&quot; imagem=&quot;cd1.jpg&quot; /&gt;
        ///  &lt;cd nome=&quot;cd3&quot; titulo=&quot;titulo2&quot; genero=&quot;genero3&quot; autor=&quot;autor3&quot; ano=&quot;2012&quot; imagem=&quot;cd1.jpg&quot; /&gt;
        ///  &lt;cd nome=&quot;cd4&quot; titulo=&quot;titulo3&quot; genero=&quot;genero3&quot; autor=&quot;autor3&quot; ano=&quot;2013&quot; imagem=&quot;cd1.jpg&quot; /&gt;
        ///  &lt;cd nome=&quot;cd5&quot; titulo=&quot;titulo4&quot; genero=&quot;genero4&quot; autor=&quot;autor4&quot; ano=&quot;2014&quot; imagem=&quot;cd1.jpg&quot; /&gt;
        ///  &lt;cd nome=&quot;c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lista_cds {
            get {
                return ResourceManager.GetString("lista_cds", resourceCulture);
            }
        }
    }
}
